<?php

namespace Panservice\FilamentUsers\Filament\Resources\UserResource\Pages;

use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Panservice\FilamentUsers\Filament\Resources\UserResource;

class EditUser extends EditRecord
{
    public function getHeading(): string|Htmlable
    {
        return __('filament-users::filament-users.resource.edit_user');
    }

    public static function getResource(): string
    {
        return config('filament-users.resource.class', UserResource::class);
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make()
                ->visible(fn (Model $record): bool => $record->id !== auth()->user()?->id)
                ->after(function () {
                    Cache::tags(config('filament-users.resource.class')::ADMIN_WIDGETS_DASHBOARD_TAG_KEY)->flush();
                }),
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if (empty($data['password'])) {
            unset($data['password']);
        }

        if (! config('filament-users.resource.roles.multiple', false)) {
            unset($data['roles']);
        }

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
